tasks:
  sign_in:
    auto_sign_in:
      user-agent: '{? headers.user_agent ?}'
      max_workers: 1
      aipocr:
        app_id: '120827608'
        api_key: 'Fl6xDdcfeZRL6OBcyZEf8dcn'
        secret_key: 'pAXatoHeeQdjxHkSMq2P0dOPTaVJOvO5'
      sites:
        m-team:
          key: '019a81a4-2578-7ac2-a87e-b33953d60d07'
    accept_all: yes
    seen:
      fields:
        - title
    notify:
      task:
        always_send: yes
        message: |+
          {%- if task.accepted -%}
          {%- for group in task.accepted|groupby('task') -%}
          FlexGet has just signed in {{ group.list|length }} sites for task {{ group.grouper }}:
          {%- for entry in group.list %}
          {{ loop.index }}: {{ entry.title }} {{ entry.result }}
          {%- endfor -%}
          {%- endfor -%}
          {%- endif -%}
          {%- if task.failed %}
          {% for group in task.failed|groupby('task') %}
          The following sites have failed for task {{ group.grouper }}:
          {%- for entry in group.list %}
          {{ loop.index }}: {{ entry.title }} {{ entry.result }} Reason: {{entry.reason|d('unknown')}}
          {%- endfor -%}
          {%- endfor -%}
          {%- endif -%}
          {%- for group in task.entries|groupby('task') %}
          {% for entry in group.list %}
          {%- if entry.messages|d('') %}
          Messages:
          {{ entry.title }} {{ entry.messages }}
          {% endif %}
          {%- endfor -%}
          {%- endfor -%}
        # 填写要使用的推送渠道，删去不需要的
        via:
          - wecom:
              corp_id: 'wwf700601ec0cdf87c'
              corp_secret: 'Z5jy2oIOh14QSatD3tUL4dYV8pcHBSzyDsyN5_q6r3A'
              agent_id: '1000002'
              to_user: 'MengJingNan'
              image: 'details_report.png'
          # Telegram 配置参见 https://flexget.com/en/Plugins/Notifiers/telegram
          - telegram:
              bot_token: 'xxxxxxxx'
              images:
                - 'details_report.png'
              recipients:
                # Chat ID 通过 @raw_data_bot (https://t.me/raw_data_bot) 获取
                - chat_id: 1694213419
              socks_proxy: socks5://user:pass@host:port
